// Generated by scripts/generate-blog-audio.mjs. Do not edit by hand.
export type BlogAudio = {
    src: string;
    bytes: number;
    characters: number;
    voice: string;
    provider: string;
};

export const BLOG_AUDIO: Record<string, BlogAudio> = {
    "codex-nightline-ai-hackathon-moving-kochi-metro": {
        src: "https://py8vbishrjiymtmr.public.blob.vercel-storage.com/audio/blog/codex-nightline-ai-hackathon-moving-kochi-metro.mp3",
        bytes: 5361408,
        characters: 4252,
        voice: "ash",
        provider: "openai",
    },
    "ieee-r10-volunteer-award": {
        src: "https://py8vbishrjiymtmr.public.blob.vercel-storage.com/audio/blog/ieee-r10-volunteer-award.mp3",
        bytes: 1122432,
        characters: 868,
        voice: "ash",
        provider: "openai",
    },
    "ieee-region-10-international-virtual-career-fair-2025": {
        src: "https://py8vbishrjiymtmr.public.blob.vercel-storage.com/audio/blog/ieee-region-10-international-virtual-career-fair-2025.mp3",
        bytes: 12970368,
        characters: 10497,
        voice: "ash",
        provider: "openai",
    },
    "ieee-sahrdaya-student-branch-movement": {
        src: "https://py8vbishrjiymtmr.public.blob.vercel-storage.com/audio/blog/ieee-sahrdaya-student-branch-movement.mp3",
        bytes: 12905472,
        characters: 10288,
        voice: "ash",
        provider: "openai",
    },
    "inclucode-2026-inclusive-software-innovation-buildathon": {
        src: "https://py8vbishrjiymtmr.public.blob.vercel-storage.com/audio/blog/inclucode-2026-inclusive-software-innovation-buildathon.mp3",
        bytes: 13312128,
        characters: 10773,
        voice: "ash",
        provider: "openai",
    },
    "ncc-thal-sainik-camp-national-bronze-medal-journey": {
        src: "https://py8vbishrjiymtmr.public.blob.vercel-storage.com/audio/blog/ncc-thal-sainik-camp-national-bronze-medal-journey.mp3",
        bytes: 17149056,
        characters: 14200,
        voice: "ash",
        provider: "openai",
    },
    "soulsync-emotional-wellness": {
        src: "https://py8vbishrjiymtmr.public.blob.vercel-storage.com/audio/blog/soulsync-emotional-wellness.mp3",
        bytes: 1359744,
        characters: 1019,
        voice: "ash",
        provider: "openai",
    },
};

export function findBlogAudio(slug?: string) {
    return slug ? BLOG_AUDIO[slug] ?? null : null;
}
