// Generated by scripts/generate-blog-audio.mjs — do not edit by hand.
export type BlogAudio = {
    src: string;
    bytes: number;
    characters: number;
    voice: string;
};

export const BLOG_AUDIO: Record<string, BlogAudio> = {
    "codex-nightline-ai-hackathon-moving-kochi-metro": {
        src: "https://py8vbishrjiymtmr.public.blob.vercel-storage.com/audio/blog/codex-nightline-ai-hackathon-moving-kochi-metro.mp3",
        bytes: 4864512,
        characters: 4252,
        voice: "aditya",
    },
    "ieee-r10-volunteer-award": {
        src: "https://py8vbishrjiymtmr.public.blob.vercel-storage.com/audio/blog/ieee-r10-volunteer-award.mp3",
        bytes: 1014144,
        characters: 868,
        voice: "aditya",
    },
    "ieee-region-10-international-virtual-career-fair-2025": {
        src: "https://py8vbishrjiymtmr.public.blob.vercel-storage.com/audio/blog/ieee-region-10-international-virtual-career-fair-2025.mp3",
        bytes: 12401280,
        characters: 10497,
        voice: "aditya",
    },
    "ieee-sahrdaya-student-branch-movement": {
        src: "https://py8vbishrjiymtmr.public.blob.vercel-storage.com/audio/blog/ieee-sahrdaya-student-branch-movement.mp3",
        bytes: 12598656,
        characters: 10288,
        voice: "aditya",
    },
    "inclucode-2026-inclusive-software-innovation-buildathon": {
        src: "https://py8vbishrjiymtmr.public.blob.vercel-storage.com/audio/blog/inclucode-2026-inclusive-software-innovation-buildathon.mp3",
        bytes: 12743424,
        characters: 10773,
        voice: "aditya",
    },
    "soulsync-emotional-wellness": {
        src: "https://py8vbishrjiymtmr.public.blob.vercel-storage.com/audio/blog/soulsync-emotional-wellness.mp3",
        bytes: 1238400,
        characters: 1019,
        voice: "aditya",
    },
};

export function findBlogAudio(slug?: string) {
    return slug ? BLOG_AUDIO[slug] ?? null : null;
}
