// Generated by scripts/generate-blog-audio.mjs — do not edit by hand.
// Empty until the MP3s are uploaded to Vercel Blob and the manifest is repointed:
//   node --experimental-strip-types scripts/generate-blog-audio.mjs --manifest-only --base-url=<blob-origin>
export type BlogAudio = {
    src: string;
    bytes: number;
    characters: number;
    voice: string;
};

export const BLOG_AUDIO: Record<string, BlogAudio> = {};

export function findBlogAudio(slug?: string) {
    return slug ? BLOG_AUDIO[slug] ?? null : null;
}
